services:
  simpleclock:
    build: .
    image: 1vangin/simpleclockapp
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt